### ISSUE TITLE
rests

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#2]
how do we handle rests?

possible ideas:
- rest is a seperate class?
- rest overloads the dot operator and returns always None for unknown attributes
- a rest is any event where all attributes are set to None apart from duration

**Comment by levinericzimmermann** [comment]
we could also take the last idea further and define rests in an even more implicit way: *a rest is any object that gets ignored by a conversion routine* e.g. a chord (as a subclass of an event) gets ignored by a monophonic instrument (that consists of a conversion routine). A potential problem from this technique could be that errors that should occur due to malformed events will pass silently because the conversion routine would just ignore them (and set them as rests).

**Comment by levinericzimmermann** [comment]
mutwo defines rests as any object that gets ignored by a conversion class
