### ISSUE TITLE
parameters of complex events

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#4]
does a complex event posess all the attributes of the events it consists of?
(does a complex event only consist of events of the same type?)
(does a complex event know anything about the type of events it consists of?)

what are potential manipulations that get backprogated onto the child events of a complex event?

**Comment by levinericzimmermann** [comment]
Because it is our current idea that ComplexEvent objects can be nested (and we want to support the use of super general objects), the 'get_parameter' method is a bit complex, because it can't just ask for the attribute (for instance if a SequentialEvent contains another SequentialEvent with very little assigned attributes, it is very like that it doesn't posses the same attribute like the final leaf, on the other hand we probably don't want to ask if an object is inherited from a SimpleEvent or from a ComplexEvent), see [commit e71b7b4647816696a76b4e81a38c9df4d6f19ec6](https://github.com/mutwo-org/mutwo/commit/e71b7b4647816696a76b4e81a38c9df4d6f19ec6).

**Comment by levinericzimmermann** [comment]
(travis ci is obviously failing due to the mentioned commit)

**Comment by levinericzimmermann** [comment]
> does a complex event posses all the attributes of the events it consists of?

no

>  (does a complex event only consist of events of the same type?)

no

>  (does a complex event know anything about the type of events it consists of?)

no

in the current implementation complex events (or better: the not-abstract classes SequentialEvent and SimultaneousEvent) are generally usable. To get, set or mutate specific parameters of events that they contain mutwo offers the methods get_paramter, set_parameter and mutate_parameter.
